server {
    listen 80;
    server_name teste.local;

    root /var/www/app/php-project-1;
    index index.php;

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
