services:

  # server
  webserver:
    image: nginx:latest
    container_name: app_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # php
  php:
    image: php:8.4-fpm
    container_name: app_php
    volumes:
      - ./php/public/:/var/www/html/public

  # Database: MariaDb
  db:
    image: mariadb:latest
    container_name: app_db
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
