server {

    listen 80;
    server_name localhost;

    # Define a pasta `public` como root para o Nginx
    root /var/www/html/public;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {

        fastcgi_pass    app_php:9000;

        fastcgi_index   index.php;

        fastcgi_param   REQUEST_METHOD $request_method;

        # fastcgi_params  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;

        include         fastcgi_params;
    }
    # Bloqueia acesso a arquivos ocultos (Ex: .git, .env)
    location ~ /\.(?!well-known).* {
        deny all;
    }

}